CREATE TABLE IF NOT EXISTS TOUR (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(500),
    PRICE DECIMAL(10, 2),
    CAPACITY INT
);
CREATE TABLE IF NOT EXISTS RESERVATION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    GUEST_REFERENCE VARCHAR(255),
    TOUR_ID BIGINT,
    STATUS VARCHAR(50)
);
